/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.gui;

import com.example.dominio.Usuario;
import com.example.servicios.GestorAplicaciones;
import com.example.servicios.GestorArchivos;
import java.awt.Frame;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Emanuel
 */
public class JDAplicacion extends javax.swing.JDialog {

    private final Usuario us;
    private File fileNvaImgApp;
    private File fileImgApp;
    private final GestorAplicaciones gestorApp;
    private final GestorArchivos gestorAr;
    private final Frame jfp;

    /**
     * Creates new form JDAplicacion
     */
    public JDAplicacion(java.awt.Frame parent, boolean modal, Usuario us) {
        super(parent, modal);
        this.jfp = parent;
        this.us = us;

        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setTitle("Nueva App");

        gestorApp = new GestorAplicaciones();
        gestorAr = new GestorArchivos();
        fileImgApp = new File(gestorAr.getImagenDefaultApp());
        JLImgApp.setIcon(new ImageIcon(fileImgApp.getAbsolutePath()));
        this.fileNvaImgApp = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPRegistrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTFNomApp = new javax.swing.JTextField();
        JBAceptar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JTFPrecioApp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JLImgApp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTADescripApp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre :");

        JTFNomApp.setToolTipText("texto");

        JBAceptar.setMnemonic('a');
        JBAceptar.setText("Aceptar");
        JBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAceptarActionPerformed(evt);
            }
        });

        JBCancelar.setMnemonic('c');
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio :");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Descripción :");

        JLImgApp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JLImgApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLImgAppMouseClicked(evt);
            }
        });

        JTADescripApp.setColumns(20);
        JTADescripApp.setRows(5);
        jScrollPane1.setViewportView(JTADescripApp);

        javax.swing.GroupLayout JPRegistrarLayout = new javax.swing.GroupLayout(JPRegistrar);
        JPRegistrar.setLayout(JPRegistrarLayout);
        JPRegistrarLayout.setHorizontalGroup(
            JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRegistrarLayout.createSequentialGroup()
                .addGroup(JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPRegistrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPRegistrarLayout.createSequentialGroup()
                                .addGroup(JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFNomApp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFPrecioApp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLImgApp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(JPRegistrarLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(JBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        JPRegistrarLayout.setVerticalGroup(
            JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPRegistrarLayout.createSequentialGroup()
                        .addGroup(JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFNomApp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFPrecioApp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(JLImgApp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(JPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBAceptar)
                    .addComponent(JBCancelar))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAceptarActionPerformed
        boolean band = true;
        String msjGestor = ""; // msj = "" --> OK / msj != "" --> Error gestores.

        // verifica que no falte ingresar información.
        if (JTFNomApp.getText().equals("") || JTFPrecioApp.getText().equals("")
                || JTADescripApp.getText().equals("")) {
            
            JOptionPane.showMessageDialog(this,
                    "Olvidó ingresar información.",
                    "Aplicaciones", JOptionPane.ERROR_MESSAGE);
            band = false;
        }
        if (JTADescripApp.getText().length()>250) {
            JOptionPane.showMessageDialog(this,
                    "Descripción demasiado extensa",
                    "Aplicaciones", JOptionPane.ERROR_MESSAGE);
            band = false;
        }

        // verifica si ha seleccionado una imagen para la aplicación.
        if (fileNvaImgApp == null && band == true) { // <--- No hay nueva imagen
            int rpt = JOptionPane.showConfirmDialog(this,
                    "No ha seleccionado una imagen para la aplicación.\nDesea hacerlo ahora?",
                    "Aplicaciones", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (rpt == 0) { // <--- YES
                band = false;
            }
        }

        // Guarda una aplicación en la tabla. 
        if (band) {
            msjGestor = gestorApp.nuevaAplicacion(JTFNomApp.getText(),
                    JTADescripApp.getText(), Double.valueOf(JTFPrecioApp.getText()),
                    us.getIdUs(), fileImgApp.getPath());

            if (msjGestor.equals("")) {
                JOptionPane.showMessageDialog(this, "Operación exitosa!!!");
                this.dispose();
                jfp.dispose();
                JFPrincipal p = new JFPrincipal(us);
                
            } else {
                JOptionPane.showMessageDialog(this, msjGestor,
                        "Aplicaciones", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_JBAceptarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.dispose();
        jfp.setEnabled(true);
        jfp.setVisible(true);
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JLImgAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLImgAppMouseClicked
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Jpg, Gif & Png imagenes", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            fileNvaImgApp = chooser.getSelectedFile();
            if (fileNvaImgApp.getName().endsWith("jpg") || this.fileNvaImgApp.getName().endsWith("png") || this.fileNvaImgApp.getName().endsWith("gif")) {
                fileImgApp = fileNvaImgApp;
            } else {
                fileNvaImgApp = null;
                JOptionPane.showMessageDialog(this, "Solo imágenes de 120 x 120px \ny con extensión .jpg, .png o .gif",
                        "Selección de Imagen", JOptionPane.ERROR_MESSAGE);
            }
            JLImgApp.setIcon(new ImageIcon(fileImgApp.getPath()));
        }
    }//GEN-LAST:event_JLImgAppMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAceptar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JLabel JLImgApp;
    private javax.swing.JPanel JPRegistrar;
    private javax.swing.JTextArea JTADescripApp;
    private javax.swing.JTextField JTFNomApp;
    private javax.swing.JTextField JTFPrecioApp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
