/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.gui;

import com.example.dominio.Aplicacion;
import com.example.dominio.Usuario;
import com.example.servicios.GestorCompras;
import com.example.servicios.GestorUsuarios;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel
 */
public class JDCalificar extends javax.swing.JDialog {

    private final GestorUsuarios gestorUs;
    private final GestorCompras gestorCompra;
    private final Usuario us;
    private final Aplicacion app;
    private JLabel[] jl = new JLabel[6];
    private int calificacion;
    private final Frame jfp;
    
    /**
     * Creates new form JDCalificar
     */
    public JDCalificar(java.awt.Frame parent, boolean modal, Usuario us, Aplicacion app) {
        super(parent, modal);
        this.jfp = parent;
        this.us = us;
        this.app = app;
        this.calificacion = 0;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setTitle("Calificar");

        gestorUs = new GestorUsuarios();
        gestorCompra = new GestorCompras();

        JLNomApp.setText(app.getNomApp());
        JLNomDev.setText("by " + gestorUs.buscarUsuario(app.getIdUsuario()).getAliasUs());

        cargaRating();
    }

    private void cargaRating() {
        // Carga en el array jl los JLabel de las estrellas
        // la posición [0] no la utilizo
        for (int i = 0; i < JPCalif.getComponentCount(); i++) {
            if (JPCalif.getComponent(i) instanceof JLabel) {
                jl[Integer.parseInt(JPCalif.getComponent(i).getName())] = (JLabel) JPCalif.getComponent(i);
            }
        }
    }

    private void estrellaSeleccionada(int e) {
        for (int i = 5; i > e; i--) {
            jl[i].setIcon(new ImageIcon("./star25.png"));
        }
        for (int i = 1; i <= e; i++) {
            jl[i].setIcon(new ImageIcon("./star25sel.png"));
        }
        calificacion = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLNomApp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLNomDev = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAComent = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        JBAceptar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JPCalif = new javax.swing.JPanel();
        JLStar1 = new javax.swing.JLabel();
        JLStar2 = new javax.swing.JLabel();
        JLStar3 = new javax.swing.JLabel();
        JLStar4 = new javax.swing.JLabel();
        JLStar5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLNomApp.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        JLNomApp.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Calificación :");

        JLNomDev.setText("by");

        JTAComent.setColumns(20);
        JTAComent.setRows(5);
        jScrollPane1.setViewportView(JTAComent);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Comentario :");

        JBAceptar.setMnemonic('a');
        JBAceptar.setText("Aceptar");
        JBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAceptarActionPerformed(evt);
            }
        });

        JBCancelar.setMnemonic('c');
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JLStar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star25.png"))); // NOI18N
        JLStar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLStar1.setName("1"); // NOI18N
        JLStar1.setRequestFocusEnabled(false);
        JLStar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLStar1MouseClicked(evt);
            }
        });

        JLStar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star25.png"))); // NOI18N
        JLStar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLStar2.setName("2"); // NOI18N
        JLStar2.setRequestFocusEnabled(false);
        JLStar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLStar2MouseClicked(evt);
            }
        });

        JLStar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star25.png"))); // NOI18N
        JLStar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLStar3.setName("3"); // NOI18N
        JLStar3.setRequestFocusEnabled(false);
        JLStar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLStar3MouseClicked(evt);
            }
        });

        JLStar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star25.png"))); // NOI18N
        JLStar4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLStar4.setName("4"); // NOI18N
        JLStar4.setRequestFocusEnabled(false);
        JLStar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLStar4MouseClicked(evt);
            }
        });

        JLStar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star25.png"))); // NOI18N
        JLStar5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLStar5.setName("5"); // NOI18N
        JLStar5.setRequestFocusEnabled(false);
        JLStar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLStar5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPCalifLayout = new javax.swing.GroupLayout(JPCalif);
        JPCalif.setLayout(JPCalifLayout);
        JPCalifLayout.setHorizontalGroup(
            JPCalifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCalifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLStar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLStar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLStar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLStar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLStar5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPCalifLayout.setVerticalGroup(
            JPCalifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLStar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(JLStar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(JLStar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(JLStar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(JLStar5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPCalif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(JBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JLNomDev, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLNomApp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JLNomApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLNomDev)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPCalif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBAceptar)
                    .addComponent(JBCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JLStar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLStar1MouseClicked
        estrellaSeleccionada(1);
    }//GEN-LAST:event_JLStar1MouseClicked

    private void JLStar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLStar2MouseClicked
        estrellaSeleccionada(2);
    }//GEN-LAST:event_JLStar2MouseClicked

    private void JLStar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLStar3MouseClicked
        estrellaSeleccionada(3);
    }//GEN-LAST:event_JLStar3MouseClicked

    private void JLStar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLStar4MouseClicked
        estrellaSeleccionada(4);
    }//GEN-LAST:event_JLStar4MouseClicked

    private void JLStar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLStar5MouseClicked
        estrellaSeleccionada(5);
    }//GEN-LAST:event_JLStar5MouseClicked

    private void JBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAceptarActionPerformed
        boolean band = true;
        if (calificacion == 0) {
            JOptionPane.showMessageDialog(this,
                    "Olvidó ingresar la calificación.",
                    "Calificar", JOptionPane.ERROR_MESSAGE);
        } else {
            if (JTAComent.getText().equals("")) {
                int rpt = JOptionPane.showConfirmDialog(this,
                        "No ha escrito un comentario.\nDesea hacerlo ahora?",
                        "Calificar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (rpt == 0) { // <--- YES
                    band = false;
                }
            }
            if (band) {
                String msjGestor = gestorCompra.calificarAppComprada(app.getIdApp(), us, calificacion, JTAComent.getText());
                if (msjGestor.equals("")) {
                    JOptionPane.showMessageDialog(this, "Operación exitosa!!!");
                    this.dispose();
                    jfp.dispose();
                    JFPrincipal p = new JFPrincipal(us);
                } else {
                    JOptionPane.showMessageDialog(this, msjGestor,
                            "Calificar", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_JBAceptarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAceptar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JLabel JLNomApp;
    private javax.swing.JLabel JLNomDev;
    private javax.swing.JLabel JLStar1;
    private javax.swing.JLabel JLStar2;
    private javax.swing.JLabel JLStar3;
    private javax.swing.JLabel JLStar4;
    private javax.swing.JLabel JLStar5;
    private javax.swing.JPanel JPCalif;
    private javax.swing.JTextArea JTAComent;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
