/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.gui;

import com.example.dominio.Aplicacion;
import com.example.dominio.Usuario;
import com.example.servicios.GestorCompras;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel
 */
public class JPApp extends javax.swing.JPanel {

    private boolean btnComprar;
    private boolean btnCalificar;
    private final Usuario us;
    private final Aplicacion app;
    private final GestorCompras gestorCompra;
    private JLabel[] jl = new JLabel[6];
    private final Frame jfp;

    /**
     * Creates new form JPApp
     */
    public JPApp(java.awt.Frame parent, Aplicacion app, boolean btnComprar, boolean btnCalificar, Usuario us) {
        this.jfp = parent;
        this.app = app;
        this.btnComprar = btnComprar;
        this.btnCalificar = btnCalificar;
        this.us = us;
        initComponents();
        this.gestorCompra = new GestorCompras();
        cargarInfoApp();
    }

    private void calificacion(int c) {
        for (int i = 0; i < JPCalif1.getComponentCount(); i++) {
            if (JPCalif1.getComponent(i) instanceof JLabel) {
                jl[Integer.parseInt(JPCalif1.getComponent(i).getName())] = (JLabel) JPCalif1.getComponent(i);
            }
        }
                for (int i = 1; i <= c; i++) {
            jl[i].setIcon(new ImageIcon("./star25sel.png"));
        }
    }

    private void cargarInfoApp() {
        JLImgApp.setIcon(new ImageIcon(app.getImagen()));
        JLNomApp.setText(app.getNomApp());
        JTADescApp.setText(app.getDescApp());
        JLPrecio.setText("Precio $ " + app.getPrecioApp());
        calificacion(app.getPuntajeApp());
        if (!btnComprar) {
            JBComprar.setVisible(false);
        }
        if (!btnCalificar) {
            JBCalificar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLImgApp = new javax.swing.JLabel();
        JLNomApp = new javax.swing.JLabel();
        JTADescApp = new javax.swing.JTextArea();
        JBComprar = new javax.swing.JButton();
        JLPuntaje = new javax.swing.JLabel();
        JLPrecio = new javax.swing.JLabel();
        JBCalificar = new javax.swing.JButton();
        JPCalif1 = new javax.swing.JPanel();
        JLStar6 = new javax.swing.JLabel();
        JLStar7 = new javax.swing.JLabel();
        JLStar8 = new javax.swing.JLabel();
        JLStar9 = new javax.swing.JLabel();
        JLStar10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        JLImgApp.setBackground(new java.awt.Color(153, 153, 255));
        JLImgApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLNomApp.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        JLNomApp.setText(".");

        JTADescApp.setEditable(false);
        JTADescApp.setColumns(20);
        JTADescApp.setRows(5);
        JTADescApp.setAutoscrolls(false);
        JTADescApp.setDoubleBuffered(true);

        JBComprar.setText("Comprar");
        JBComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBComprarActionPerformed(evt);
            }
        });

        JLPuntaje.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        JLPuntaje.setText("Calificación:");

        JLPrecio.setText(".");

        JBCalificar.setText("Calificar");
        JBCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCalificarActionPerformed(evt);
            }
        });

        JLStar6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLStar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star25.png"))); // NOI18N
        JLStar6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLStar6.setName("1"); // NOI18N
        JLStar6.setRequestFocusEnabled(false);

        JLStar7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLStar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star25.png"))); // NOI18N
        JLStar7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLStar7.setName("2"); // NOI18N
        JLStar7.setRequestFocusEnabled(false);

        JLStar8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLStar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star25.png"))); // NOI18N
        JLStar8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLStar8.setName("3"); // NOI18N
        JLStar8.setRequestFocusEnabled(false);

        JLStar9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLStar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star25.png"))); // NOI18N
        JLStar9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLStar9.setName("4"); // NOI18N
        JLStar9.setRequestFocusEnabled(false);

        JLStar10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLStar10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star25.png"))); // NOI18N
        JLStar10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLStar10.setName("5"); // NOI18N
        JLStar10.setRequestFocusEnabled(false);

        javax.swing.GroupLayout JPCalif1Layout = new javax.swing.GroupLayout(JPCalif1);
        JPCalif1.setLayout(JPCalif1Layout);
        JPCalif1Layout.setHorizontalGroup(
            JPCalif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCalif1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLStar6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLStar7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLStar8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLStar9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLStar10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPCalif1Layout.setVerticalGroup(
            JPCalif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLStar7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(JLStar6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(JLStar8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(JLStar9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(JLStar10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLImgApp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JLNomApp, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JLPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(JPCalif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBCalificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTADescApp)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLNomApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTADescApp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBComprar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBCalificar)
                    .addComponent(JPCalif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(JLImgApp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBComprarActionPerformed
        int rpt = JOptionPane.showConfirmDialog(this,
                "Desea comprar la aplicación " + app.getNomApp() + " ?",
                "Carrito de compras",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (rpt == 0) {
            if (gestorCompra.nuevaCompra(app.getIdApp(), us.getIdUs())) {
                JBComprar.setVisible(false);
                JBCalificar.setVisible(true);
                JOptionPane.showMessageDialog(this, "Operación exitosa!!!");
                jfp.dispose();
                JFPrincipal p = new JFPrincipal(us);
            } else {
                JOptionPane.showMessageDialog(this, "La compra no se ha podido concretar.\nInténtelo nuevamente.");
            }
        }
    }//GEN-LAST:event_JBComprarActionPerformed

    private void JBCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCalificarActionPerformed
        int rpt = JOptionPane.showConfirmDialog(this,
                "Desea calificar la aplicación " + app.getNomApp() + " ?",
                "Calificar",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (rpt == 0) {
            this.setEnabled(false);
            JDCalificar jdc = new JDCalificar(jfp, false, us, app);
        }
    }//GEN-LAST:event_JBCalificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCalificar;
    private javax.swing.JButton JBComprar;
    private javax.swing.JLabel JLImgApp;
    private javax.swing.JLabel JLNomApp;
    private javax.swing.JLabel JLPrecio;
    private javax.swing.JLabel JLPuntaje;
    private javax.swing.JLabel JLStar1;
    private javax.swing.JLabel JLStar10;
    private javax.swing.JLabel JLStar2;
    private javax.swing.JLabel JLStar3;
    private javax.swing.JLabel JLStar4;
    private javax.swing.JLabel JLStar5;
    private javax.swing.JLabel JLStar6;
    private javax.swing.JLabel JLStar7;
    private javax.swing.JLabel JLStar8;
    private javax.swing.JLabel JLStar9;
    private javax.swing.JPanel JPCalif;
    private javax.swing.JPanel JPCalif1;
    private javax.swing.JTextArea JTADescApp;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
